# Generated by Django 3.2.6 on 2021-09-25 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_buisness'),
    ]

    operations = [
        migrations.AddField(
            model_name='buisness',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
